function s = calc_dr(x, dx, r)

x1 = x(1);
x2 = x(2);
x3 = x(3);

dx1 = dx(1);
dx2 = dx(2);
dx3 = dx(3);

%CUT_DR
%    S = CUT_DR(DX1,DX2,DX3,R,X1,X2,X3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    11-Aug-2017 14:52:50

t2 = dx1.^2;
t3 = dx2.^2;
t4 = r.^2;
t5 = dx3.^2;
t6 = x1.^2;
t7 = x3.^2;
t8 = x2.^2;
t9 = t2+t3+t5;
t10 = 1.0./t9;
t11 = dx1.*x1;
t12 = dx2.*x2;
t13 = dx3.*x3;
t14 = t2.*t4;
t15 = t3.*t4;
t16 = t4.*t5;
t17 = dx1.*dx2.*x1.*x2.*2.0;
t18 = dx1.*dx3.*x1.*x3.*2.0;
t19 = dx2.*dx3.*x2.*x3.*2.0;
t20 = t14+t15+t16+t17+t18+t19-t2.*t7-t3.*t6-t2.*t8-t3.*t7-t5.*t6-t5.*t8;
t21 = sqrt(t20);
s = [-t10.*(t11+t12+t13+t21);-t10.*(t11+t12+t13-t21)];
