function dJ_w = dJ_w_fcn(Th1,Th2,Th3,Th4,W1,W2,W3,W4)
%DJ_W_FCN
%    DJ_W = DJ_W_FCN(TH1,TH2,TH3,TH4,W1,W2,W3,W4)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    27-Jul-2017 21:57:09

t2 = sqrt(2.0);
t3 = cos(Th1);
t4 = W1.*t2.*t3.*5.0e-5;
t5 = cos(Th2);
t6 = cos(Th3);
t7 = cos(Th4);
t8 = W4.*t2.*t7.*5.0e-5;
t9 = sin(Th1);
t10 = sin(Th2);
t11 = sin(Th3);
t12 = sin(Th4);
t13 = t2.*t3.*1.5e-6;
t14 = t2.*t9.*1.25e-5;
t15 = t13+t14;
t16 = t2.*t5.*1.5e-6;
t17 = t16-t2.*t10.*1.25e-5;
t18 = t2.*t6.*1.5e-6;
t19 = t2.*t11.*1.25e-5;
t20 = t18+t19;
t21 = W3.*t20;
t22 = t2.*t7.*1.5e-6;
t23 = t22-t2.*t12.*1.25e-5;
t24 = W4.*t23;
dJ_w = reshape([t4,-t4,W1.*t9.*(-1.0e-4),-W1.*t15,W1.*t15,-W1.*(t3.*2.5e-5-t9.*3.0e-6),W2.*t2.*t5.*(-5.0e-5),W2.*t2.*t5.*(-5.0e-5),W2.*t10.*1.0e-4,-W2.*t17,-W2.*t17,W2.*(t5.*2.5e-5+t10.*3.0e-6),W3.*t2.*t6.*(-5.0e-5),W3.*t2.*t6.*5.0e-5,W3.*t11.*(-1.0e-4),t21,-t21,-W3.*(t6.*2.5e-5-t11.*3.0e-6),t8,t8,W4.*t12.*1.0e-4,t24,t24,W4.*(t7.*2.5e-5+t12.*3.0e-6)],[6,4]);
