function J = J_fcn(Th1,Th2,Th3,Th4)
%J_FCN
%    J = J_FCN(TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    18-Jul-2017 20:56:44

t2 = sqrt(2.0);
t3 = sin(Th1);
t4 = t2.*t3.*1.25e-5;
t5 = sin(Th2);
t6 = sin(Th3);
t7 = sin(Th4);
t8 = t2.*t7.*1.25e-5;
t9 = cos(Th1);
t10 = cos(Th2);
t11 = cos(Th3);
t12 = cos(Th4);
t13 = t2.*t9.*2.5e-6;
t14 = t2.*t5.*(-5.0e-7)-t2.*t10.*2.5e-6;
t15 = t2.*t6.*5.0e-7;
t16 = t2.*t12.*2.5e-6;
t17 = t2.*t7.*5.0e-7;
t18 = t16+t17;
J = reshape([t4,-t4,t9.*2.5e-5,t13-t2.*t3.*5.0e-7,-t13+t2.*t3.*5.0e-7,t3.*(-5.0e-6)-t9.*1.0e-6,t2.*t5.*(-1.25e-5),t2.*t5.*(-1.25e-5),t10.*(-2.5e-5),t14,t14,t5.*5.0e-6-t10.*1.0e-6,t2.*t6.*(-1.25e-5),t2.*t6.*1.25e-5,t11.*2.5e-5,t15-t2.*t11.*2.5e-6,-t15+t2.*t11.*2.5e-6,t6.*(-5.0e-6)-t11.*1.0e-6,t8,t8,t12.*(-2.5e-5),t18,t18,t7.*5.0e-6-t12.*1.0e-6],[6,4]);
