function s = Th1(Th2,f1,f2,f3)
%TH1
%    S = TH1(TH2,F1,F2,F3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    15-Nov-2017 19:15:06

t2 = sqrt(2.0);
t3 = tan(Th2);
s = -atan((f1.*t2.*t3-f2.*t2.*t3)./(f1.*t2+f2.*t2-f3.*t3.*2.0));
