function F = F_own_fnc(Th1,Th2,Th3,Th4,W1,W2,W3,W4)
%F_OWN_FNC
%    F = F_OWN_FNC(TH1,TH2,TH3,TH4,W1,W2,W3,W4)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Nov-2017 21:59:57

t2 = sqrt(2.0);
t3 = sin(Th1);
t4 = W1.*t2.*t3.*9.95e-6;
t5 = sin(Th2);
t6 = sin(Th3);
t7 = sin(Th4);
t8 = W4.*t2.*t7.*9.95e-6;
t9 = cos(Th1);
t10 = cos(Th2);
t11 = cos(Th3);
t12 = cos(Th4);
t13 = W1.*t2.*t9.*2.4875e-6;
t14 = W4.*t2.*t12.*2.4875e-6;
t15 = W3.*t2.*t6.*1.5e-6;
t16 = W4.*t2.*t7.*1.5e-6;
F = [t4+t8-W2.*t2.*t5.*9.95e-6-W3.*t2.*t6.*9.95e-6;-t4+t8-W2.*t2.*t5.*9.95e-6+W3.*t2.*t6.*9.95e-6;W1.*t9.*1.99e-5-W2.*t10.*1.99e-5+W3.*t11.*1.99e-5-W4.*t12.*1.99e-5;t13+t14+t15+t16-W1.*t2.*t3.*1.5e-6-W2.*t2.*t5.*1.5e-6-W2.*t2.*t10.*2.4875e-6-W3.*t2.*t11.*2.4875e-6;-t13+t14-t15+t16+W1.*t2.*t3.*1.5e-6-W2.*t2.*t5.*1.5e-6-W2.*t2.*t10.*2.4875e-6+W3.*t2.*t11.*2.4875e-6;W1.*t3.*(-4.975e-6)+W2.*t5.*4.975e-6-W3.*t6.*4.975e-6-W1.*t9.*3.0e-6+W4.*t7.*4.975e-6-W2.*t10.*3.0e-6-W3.*t11.*3.0e-6-W4.*t12.*3.0e-6];
