function out1 = resolve_th(y1,y2)
%RESOLVE_TH
%    OUT1 = RESOLVE_TH(Y1,Y2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Aug-2017 21:39:11

t2 = y1.^2;
t3 = y2.^2;
t4 = t2.*4.0;
t5 = t3.*4.0;
t6 = t4+t5+1.0./2.0;
t7 = sqrt(t6);
t8 = sqrt(2.0);
t9 = t2+t3;
t10 = 1.0./t9;
t11 = t7.*y1.*2.0;
t12 = t7.*y2.*2.0;
t13 = t8.*y1;
t14 = t8.*y2;
t15 = t11+t12+t13+t14;
t16 = y1+y2;
t17 = 1.0./t16;
t18 = y1-y2;
t19 = t11+t12-t13-t14;
t20 = t10.*t17.*t18.*t19.*(1.0./4.0);
t21 = t10.*t19.*(1.0./4.0);
out1 = reshape([t10.*t15.*t17.*t18.*(-1.0./4.0),t20,t10.*t15.*(-1.0./4.0),t21,t10.*t15.*t17.*t18.*(1.0./4.0),-t20,t10.*t15.*(1.0./4.0),-t21],[2,4]);
