function s3 = ellipsoidBoundary(a,b,c,dx,dy,dz,x,y,z)
%ELLIPSOIDBOUNDARY
%    S3 = ELLIPSOIDBOUNDARY(A,B,C,DX,DY,DZ,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Aug-2017 21:29:33

t2 = a.^2;
t3 = b.^2;
t4 = c.^2;
t5 = dz.^2;
t6 = t2.*t3.*t5;
t7 = dy.^2;
t8 = t2.*t4.*t7;
t9 = dx.^2;
t10 = t3.*t4.*t9;
t11 = z.^2;
t12 = t2.*t3.*t11;
t13 = y.^2;
t14 = t2.*t4.*t13;
t15 = x.^2;
t16 = t3.*t4.*t15;
t17 = dx.*t3.*t4.*x.*2.0;
t18 = dy.*t2.*t4.*y.*2.0;
t19 = dz.*t2.*t3.*z.*2.0;
t20 = t6+t8+t10+t12+t14+t16+t17+t18+t19;
t21 = 1.0./sqrt(t20);
t22 = a.*b.*c.*t21;
s3 = [t22;-t22];
