function s1 = ellipsoidBoundaryInside(a,b,c,dx,dy,dz,x,y,z)
%ELLIPSOIDBOUNDARYINSIDE
%    S1 = ELLIPSOIDBOUNDARYINSIDE(A,B,C,DX,DY,DZ,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Aug-2017 16:36:40

t2 = a.^2;
t3 = b.^2;
t4 = c.^2;
t5 = dz.^2;
t6 = t2.*t3.*t5;
t7 = dy.^2;
t8 = t2.*t4.*t7;
t9 = dx.^2;
t10 = t3.*t4.*t9;
t11 = x.^2;
t12 = z.^2;
t13 = y.^2;
t14 = t6+t8+t10;
t15 = 1.0./t14;
t16 = dx.*dy.*t4.*x.*y.*2.0;
t17 = dx.*dz.*t3.*x.*z.*2.0;
t18 = dy.*dz.*t2.*y.*z.*2.0;
t19 = t6+t8+t10+t16+t17+t18-t3.*t5.*t11-t2.*t5.*t13-t2.*t7.*t12-t4.*t7.*t11-t3.*t9.*t12-t4.*t9.*t13;
t20 = sqrt(t19);
t21 = a.*b.*c.*t20;
t22 = dx.*t3.*t4.*x;
t23 = dy.*t2.*t4.*y;
t24 = dz.*t2.*t3.*z;
s1 = [-t15.*(t21+t22+t23+t24);-t15.*(-t21+t22+t23+t24)];
